# Generated by Django 3.2.7 on 2021-09-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='appoinment',
            old_name='patient',
            new_name='Patient',
        ),
    ]
