# Generated by Django 3.2.7 on 2021-09-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_auto_20210919_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appoinment',
            old_name='Patient',
            new_name='patient',
        ),
    ]
